name: Build Android 8 for ARM64 with QEMU support

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk
          sudo apt-get install -y libwxgtk3.0-dev

      - name: Download repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH

      - name: Initialize AOSP repository
        run: |
          mkdir ~/aosp
          cd ~/aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r1
          repo sync -j4

      - name: Download kernel source
        run: |
          cd ~/aosp
          git clone --depth=1 https://android.googlesource.com/kernel/common kernel
          cd kernel
          git checkout android-3.18

      - name: Configure kernel
        run: |
          cd ~/aosp/kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- menuconfig

      - name: Enable virtio devices in kernel config
        run: |
          cd ~/aosp/kernel
          scripts/config --enable CONFIG_VIRTIO
          scripts/config --enable CONFIG_VIRTIO_BLK
          scripts/config --enable CONFIG_VIRTIO_NET

      - name: Build kernel
        run: |
          cd ~/aosp/kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Set up environment
        run: |
          cd ~/aosp
          source build/envsetup.sh
          lunch aosp_arm64-userdebug

      - name: Build Android
        run: |
          cd ~/aosp
          make -j$(nproc)

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android_build_output
          path: |
            ~/aosp/out/target/product/generic/*.img
            ~/aosp/out/target/product/generic/*.zip
            
