name: Build Android 8 for ARM64 with QEMU support

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk

      - name: Download and install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod +x ~/bin/repo
          export PATH=~/bin:$PATH

      - name: Verify repo installation
        run: |
          which repo
          repo --version

      - name: Clone AOSP repository
        run: |
          mkdir ~/aosp
          cd ~/aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r1
          repo sync -j4

      # Continue with the rest of your workflow...
